### ISSUE TITLE
face3d error

### ISSUE THREAD

**Issue by reinmj** [KwaiVGI/LivePortrait#10]
(LivePortrait) PS J:\githubs\LivePortrait> python .\inference.py
ERROR:albumentations.check_version:Error fetching version info
Traceback (most recent call last):
  File "I:\anaconda3\envs\LivePortrait\lib\site-packages\albumentations\check_version.py", line 32, in fetch_version_info
    data = response.read()
  File "I:\anaconda3\envs\LivePortrait\lib\http\client.py", line 476, in read
    s = self._safe_read(self.length)
  File "I:\anaconda3\envs\LivePortrait\lib\http\client.py", line 626, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "I:\anaconda3\envs\LivePortrait\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "I:\anaconda3\envs\LivePortrait\lib\ssl.py", line 1275, in recv_into
    return self.read(nbytes, buffer)
  File "I:\anaconda3\envs\LivePortrait\lib\ssl.py", line 1133, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
Traceback (most recent call last):
  File "J:\githubs\LivePortrait\inference.py", line 7, in <module>
    from src.live_portrait_pipeline import LivePortraitPipeline
  File "J:\githubs\LivePortrait\src\live_portrait_pipeline.py", line 20, in <module>
    from .utils.cropper import Cropper
  File "J:\githubs\LivePortrait\src\utils\cropper.py", line 10, in <module>
    from .face_analysis_diy import FaceAnalysisDIY
  File "J:\githubs\LivePortrait\src\utils\face_analysis_diy.py", line 9, in <module>
    from .dependencies.insightface.app import FaceAnalysis
  File "J:\githubs\LivePortrait\src\utils\dependencies\insightface\__init__.py", line 18, in <module>
    from . import app
  File "J:\githubs\LivePortrait\src\utils\dependencies\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "J:\githubs\LivePortrait\src\utils\dependencies\insightface\app\mask_renderer.py", line 8, in <module>
    from ..thirdparty import face3d
  File "J:\githubs\LivePortrait\src\utils\dependencies\insightface\thirdparty\face3d\__init__.py", line 3, in <module>
    from . import mesh
  File "J:\githubs\LivePortrait\src\utils\dependencies\insightface\thirdparty\face3d\mesh\__init__.py", line 9, in <module>
    from .cython import mesh_core_cython
ImportError: cannot import name 'mesh_core_cython' from 'src.utils.dependencies.insightface.thirdparty.face3d.mesh.cython' (unknown location)

anyone has this error ? how to fixed ?

**Comment by cleardusk** [comment]
Thanks for your attention. There is a similar issue here: [https://github.com/KwaiVGI/LivePortrait/issues/8](https://github.com/KwaiVGI/LivePortrait/issues/8)

**Comment by zzzweakman** [comment]
> (LivePortrait) PS J:\githubs\LivePortrait> python .\inference.py ERROR:albumentations.check_version:Error fetching version info Traceback (most recent call last): File "I:\anaconda3\envs\LivePortrait\lib\site-packages\albumentations\check_version.py", line 32, in fetch_version_info data = response.read() File "I:\anaconda3\envs\LivePortrait\lib\http\client.py", line 476, in read s = self._safe_read(self.length) File "I:\anaconda3\envs\LivePortrait\lib\http\client.py", line 626, in _safe_read chunk = self.fp.read(min(amt, MAXAMOUNT)) File "I:\anaconda3\envs\LivePortrait\lib\socket.py", line 704, in readinto return self._sock.recv_into(b) File "I:\anaconda3\envs\LivePortrait\lib\ssl.py", line 1275, in recv_into return self.read(nbytes, buffer) File "I:\anaconda3\envs\LivePortrait\lib\ssl.py", line 1133, in read return self._sslobj.read(len, buffer) socket.timeout: The read operation timed out Traceback (most recent call last): File "J:\githubs\LivePortrait\inference.py", line 7, in from src.live_portrait_pipeline import LivePortraitPipeline File "J:\githubs\LivePortrait\src\live_portrait_pipeline.py", line 20, in from .utils.cropper import Cropper File "J:\githubs\LivePortrait\src\utils\cropper.py", line 10, in from .face_analysis_diy import FaceAnalysisDIY File "J:\githubs\LivePortrait\src\utils\face_analysis_diy.py", line 9, in from .dependencies.insightface.app import FaceAnalysis File "J:\githubs\LivePortrait\src\utils\dependencies\insightface__init__.py", line 18, in from . import app File "J:\githubs\LivePortrait\src\utils\dependencies\insightface\app__init__.py", line 2, in from .mask_renderer import * File "J:\githubs\LivePortrait\src\utils\dependencies\insightface\app\mask_renderer.py", line 8, in from ..thirdparty import face3d File "J:\githubs\LivePortrait\src\utils\dependencies\insightface\thirdparty\face3d__init_.py", line 3, in from . import mesh File "J:\githubs\LivePortrait\src\utils\dependencies\insightface\thirdparty\face3d\mesh__init_.py", line 9, in from .cython import mesh_core_cython ImportError: cannot import name 'mesh_core_cython' from 'src.utils.dependencies.insightface.thirdparty.face3d.mesh.cython' (unknown location)__
> 
> anyone has this error ? how to fixed ?

We have fixed it in  #26 , just pull it to update! @jonk999
