### ISSUE TITLE
使用LivePortrait遇到的问题

### ISSUE THREAD

**Issue by gandlf-web** [KwaiVGI/LivePortrait#146]
你好，我在使用LivePortrait遇到了如下的问题：
D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:891 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

File "F:\workstation\ComfyUI-aki-v1.3.7\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "F:\workstation\ComfyUI-aki-v1.3.7\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "F:\workstation\ComfyUI-aki-v1.3.7\execution.py", line 66, in map_node_over_list
results.append(getattr(obj, func)(**input_data_all))
File "F:\workstation\ComfyUI-aki-v1.3.7\custom_nodes\comfyui-liveportrait\nodes\live_portrait.py", line 364, in run
live_portrait_pipeline = LivePortraitPipeline(
File "F:\workstation\ComfyUI-aki-v1.3.7\custom_nodes\comfyui-liveportrait\nodes\LivePortrait\src\live_portrait_pipeline.py", line 68, in __init__
self.cropper = Cropper(crop_cfg=crop_cfg,landmark_runner_ckpt=landmark_runner_ckpt,insightface_pretrained_weights=insightface_pretrained_weights)
File "F:\workstation\ComfyUI-aki-v1.3.7\custom_nodes\comfyui-liveportrait\nodes\LivePortrait\src\utils\cropper.py", line 45, in __init__
self.landmark_runner = LandmarkRunner(
File "F:\workstation\ComfyUI-aki-v1.3.7\custom_nodes\comfyui-liveportrait\nodes\LivePortrait\src\utils\landmark_runner.py", line 36, in __init__
self.session = onnxruntime.InferenceSession(
File "F:\workstation\ComfyUI-aki-v1.3.7\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 432, in __init__
raise fallback_error from e
File "F:\workstation\ComfyUI-aki-v1.3.7\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 427, in __init__
self._create_inference_session(self._fallback_providers, None)
File "F:\workstation\ComfyUI-aki-v1.3.7\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
sess.initialize_session(providers, provider_options, disabled_optimizers)

**Comment by westNeighbor** [comment]
install onnxruntime-gpu as this `pip install onnxruntime-gpu==1.18.0 --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/`

**Comment by shalevc1098** [comment]
> pip install onnxruntime-gpu==1.18.0 --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/

```
[17:55:31] Load appearance_feature_extractor done.                                           live_portrait_wrapper.py:36
[17:55:32] Load motion_extractor done.                                                       live_portrait_wrapper.py:39
           Load warping_module done.                                                         live_portrait_wrapper.py:42
           Load spade_generator done.                                                        live_portrait_wrapper.py:45
           Load stitching_retargeting_module done.                                           live_portrait_wrapper.py:49
2024-07-16 17:55:32.8802277 [E:onnxruntime:Default, provider_bridge_ort.cc:1744 onnxruntime::TryGetProviderInfo_CUDA] C:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1426 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\AI\LivePortrait\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

*************** EP Error ***************
EP Error C:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:866 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.
 when using [('CUDAExecutionProvider', {'device_id': 0})]
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-07-16 17:55:32.9229832 [E:onnxruntime:Default, provider_bridge_ort.cc:1744 onnxruntime::TryGetProviderInfo_CUDA] C:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1426 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\AI\LivePortrait\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Traceback (most recent call last):
  File "C:\AI\LivePortrait\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\AI\LivePortrait\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: C:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:866 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\AI\LivePortrait\app.py", line 42, in <module>
    gradio_pipeline = GradioPipeline(
  File "C:\AI\LivePortrait\src\gradio_pipeline.py", line 28, in __init__
    super().__init__(inference_cfg, crop_cfg)
  File "C:\AI\LivePortrait\src\live_portrait_pipeline.py", line 38, in __init__
    self.cropper: Cropper = Cropper(crop_cfg=crop_cfg)
  File "C:\AI\LivePortrait\src\utils\cropper.py", line 50, in __init__
    self.landmark_runner = LandmarkRunner(
  File "C:\AI\LivePortrait\src\utils\landmark_runner.py", line 37, in __init__
    self.session = onnxruntime.InferenceSession(
  File "C:\AI\LivePortrait\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 432, in __init__
    raise fallback_error from e
  File "C:\AI\LivePortrait\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 427, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "C:\AI\LivePortrait\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: C:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:866 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.```

**Comment by westNeighbor** [comment]
cuda, cudnn, versions? https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements

**Comment by shalevc1098** [comment]
12.1 and they said that 18 should work with any 12 version

**Comment by westNeighbor** [comment]
Not clear, If you have right versions of torch, onnxruntime, cuda, cudnn, it should work.

**Comment by shalevc1098** [comment]
> westNeighbor

i have the one for 12.1
--extra-index-url https://download.pytorch.org/whl/cu121
torch==2.3.0
torchvision==0.18.0
torchaudio==2.3.0

**Comment by shalevc1098** [comment]
![image](https://github.com/user-attachments/assets/1d263176-a236-41f1-9b9f-afac79bd32e6)

**Comment by westNeighbor** [comment]
Your torch is right. And your onnxtrumtime finds the CUDA too. No idea what's the reason. I'm using CUDA 12.4, it works. Maybe you can try reinstalling or install different onnxruntime-gpu version to test.

**Comment by westNeighbor** [comment]
pip list should show
torch                  2.3.0+cu121
torchaudio             2.3.0+cu121
torchvision            0.18.0+cu121

**Comment by shalevc1098** [comment]
> pip list should show torch 2.3.0+cu121 torchaudio 2.3.0+cu121 torchvision 0.18.0+cu121
![image](https://github.com/user-attachments/assets/8224067f-733e-4ff0-be11-f378ff538ea8)

**Comment by shalevc1098** [comment]
i don't want to install cuda 12.4 so i wouldn't accidentally screw other python projects i use

**Comment by shalevc1098** [comment]
> > i don't want to install cuda 12.4 so i wouldn't accidentally screw other python projects i use
> 
> pyenv every time. dont contaminate other projects make them independant

yes but because i have a project that uses cuda 12.1, if i would install cuda 12.4 instead of what i have i don't want to make it to stop working

**Comment by hunglsxx** [comment]
@shalevc1098 Have you found a solution yet? I'm experiencing a similar issue. Although the application is still running, there is always a notification like the one in the picture.

<img width="1082" alt="Screenshot 2024-08-06 at 10 38 39" src="https://github.com/user-attachments/assets/d47701e2-e704-4dcb-93ee-0c525dbdb13d">


> > > Tôi không muốn cài đặt cuda 12.4 vì vậy tôi không muốn vô tình làm hỏng các dự án python khác mà tôi sử dụng
> > 
> > 
> > pyenv mọi lúc. không làm ô nhiễm các dự án khác, làm cho chúng độc lập
> 
> vâng nhưng vì tôi có một dự án sử dụng cuda 12.1, nếu tôi cài đặt cuda 12.4 thay vì cái tôi đang có thì tôi không muốn nó ngừng hoạt động

**Comment by FurkanGozukara** [comment]
proper python cuda c++ tools installation explained in this tutorial : 


### [**Essential AI Tools and Libraries: A Guide to Python, Git, C++ Compile Tools, FFmpeg, CUDA, PyTorch**](https://youtu.be/-NjNy7afOQ0)

[![image](https://cdn-uploads.huggingface.co/production/uploads/6345bd89fe134dfd7a0dba40/uSxPD2Yav4JlLEAHQE5Dr.png)](https://youtu.be/-NjNy7afOQ0)

**Comment by thinkingyuan** [comment]
I hava the same problem.

here is the library version detail:

onnxruntime.version=1.18.0
torch.cuda_version=12.1
torch.cuda.is_available()=True

(liveportrait) D:\>pip list | grep torch
torch                     2.3.0+cu121
torchaudio            2.3.0+cu121
torchvision            0.18.0+cu121

os:windows 10

**Comment by rmasiso** [comment]
Also suffering through this error. PATHs have been set, cuda is available, cudnn is installed (multiple were tried to see if it was a cudnn version that wasn't working); and even with the 1 click windows installation, I get the same error posted in this issue.
