### ISSUE TITLE
ValueError: mutable default <class 'numpy.ndarray'>

### ISSUE THREAD

**Issue by Nisekoi-1** [KwaiVGI/LivePortrait#149]
```
Traceback (most recent call last):
  File "D:\AI\LivePortrait\inference.py", line 7, in <module>
    from src.config.inference_config import InferenceConfig
  File "D:\AI\LivePortrait\src\config\inference_config.py", line 15, in <module>
    @dataclass(repr=False)  # use repr from PrintableConfig
     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VICTUS\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 1222, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VICTUS\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VICTUS\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'numpy.ndarray'> for field mask_crop is not allowed: use default_factory
```

**Comment by Nisekoi-1** [comment]
hii, how can i fix this?

**Comment by cleardusk** [comment]
It seems your mask_template file does not exist: https://github.com/KwaiVGI/LivePortrait/blob/main/src/utils/resources/mask_template.png or not loaded correctly. @Nisekoi-1

**Comment by AbnerVictor** [comment]
Same issue, have you fixed the problem?

**Comment by AbnerVictor** [comment]
> It seems your mask_template file does not exist or is not loaded correctly: https://github.com/KwaiVGI/LivePortrait/blob/main/src/utils/resources/mask_template.png . @Nisekoi-1

I have the image downloaded at the exact path, but the problem remains

**Comment by cleardusk** [comment]
Could you give it a try as follows? @AbnerVictor @Nisekoi-1 
https://github.com/KwaiVGI/LivePortrait/blob/54e50986b232fc3f382f20924cdff675c0ce729d/src/config/inference_config.py#L49

to 
```python
from dataclasses import dataclass, field

mask_crop: ndarray = field(default_factory=lambda: cv2.imread(make_abs_path('../utils/resources/mask_template.png'), cv2.IMREAD_COLOR))
```
