### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable using example for vid2vid

### ISSUE THREAD

**Issue by x4080** [KwaiVGI/LivePortrait#197]
```
python inference.py -s assets/examples/driving/d6.mp4 -d assets/examples/driving/d3.pkl
```

error result
```
Traceback (most recent call last):
  File "/Volumes/VGenNVME/LivePortrait/inference.py", line 57, in <module>
    main()
  File "/Volumes/VGenNVME/LivePortrait/inference.py", line 53, in main
    live_portrait_pipeline.execute(args)
  File "/Volumes/VGenNVME/LivePortrait/src/live_portrait_pipeline.py", line 252, in execute
    lip_delta_before_animation = self.live_portrait_wrapper.retarget_lip(x_s, combined_lip_ratio_tensor_before_animation)
  File "/Volumes/VGenNVME/LivePortrait/src/live_portrait_wrapper.py", line 230, in retarget_lip
    delta = self.stitching_retargeting_module['lip'](feat_lip)
TypeError: 'NoneType' object is not subscriptable
```

What is the correct way to inference ?

**Comment by zzzweakman** [comment]
Thank you for your attention. This is similar to #181. Could you please verify if the size of your `stitching_retargeting_module.pth` match the size indicated in the [table](https://github.com/KwaiVGI/LivePortrait?tab=readme-ov-file#5-inference-speed-evaluation-) in the README? @x4080

**Comment by x4080** [comment]
@zzzweakman Thanks for the hint, thats the answer, I was using older version and I was moving around the model, but thats solve it
