### ISSUE TITLE
macos 没 UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by lm2024** [KwaiVGI/LivePortrait#232]

**Comment by lm2024** [comment]
(LivePortrait39) ➜  LivePortrait git:(main) PYTORCH_ENABLE_MPS_FALLBACK=1 python inference.py
Traceback (most recent call last):
  File "/Users/zhanglimin/Documents/ideaProject/ai/LivePortrait/LivePortrait/inference.py", line 62, in <module>
    main()
  File "/Users/zhanglimin/Documents/ideaProject/ai/LivePortrait/LivePortrait/inference.py", line 52, in main
    live_portrait_pipeline = LivePortraitPipeline(
  File "/Users/zhanglimin/Documents/ideaProject/ai/LivePortrait/LivePortrait/src/live_portrait_pipeline.py", line 38, in __init__
    self.live_portrait_wrapper: LivePortraitWrapper = LivePortraitWrapper(inference_cfg=inference_cfg)
  File "/Users/zhanglimin/Documents/ideaProject/ai/LivePortrait/LivePortrait/src/live_portrait_wrapper.py", line 39, in __init__
    self.appearance_feature_extractor = load_model(inference_cfg.checkpoint_F, model_config, self.device, 'appearance_feature_extractor')
  File "/Users/zhanglimin/Documents/ideaProject/ai/LivePortrait/LivePortrait/src/utils/helper.py", line 144, in load_model
    model.load_state_dict(torch.load(ckpt_path, map_location=lambda storage, loc: storage))
  File "/opt/miniconda3/envs/LivePortrait39/lib/python3.9/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/miniconda3/envs/LivePortrait39/lib/python3.9/site-packages/torch/serialization.py", line 1262, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by lm2024** [comment]
这种情况怎么办？ 我无法继续执行了？ 上面的其他步骤我都按要求执行过了。

**Comment by zzzweakman** [comment]
> 这种情况怎么办？ 我无法继续执行了？ 上面的其他步骤我都按要求执行过了。

您好，您可以确认一下模型被正确下载到对应的路径了吗？以及他是否和我们readme中给出的模型文件大小一致？这有可能是文件损坏导致的。

Thank you for your attention! Could you confirm that all the weights are placed in the correct location and that their sizes match those indicated in the [table](https://github.com/KwaiVGI/LivePortrait?tab=readme-ov-file#5-inference-speed-evaluation-) in the readme? @lm2024
