### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by jonk999** [KwaiVGI/LivePortrait#25]
I've gone through the steps on the main page to install. Setup environment, install requirements and gradio as well as the models. I get the same error whether I use a conda env or python one.
When running python inference.py or python app.py I get the following:
```
(venv) I:\zzzz_stablediffusion-other\zz_LP\LivePortrait>python app.py
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
Traceback (most recent call last):
  File "I:\zzzz_stablediffusion-other\zz_LP\LivePortrait\app.py", line 11, in <module>
    from src.gradio_pipeline import GradioPipeline
  File "I:\zzzz_stablediffusion-other\zz_LP\LivePortrait\src\gradio_pipeline.py", line 8, in <module>
    from .live_portrait_pipeline import LivePortraitPipeline
  File "I:\zzzz_stablediffusion-other\zz_LP\LivePortrait\src\live_portrait_pipeline.py", line 20, in <module>
    from .utils.cropper import Cropper
  File "I:\zzzz_stablediffusion-other\zz_LP\LivePortrait\src\utils\cropper.py", line 11, in <module>
    from .face_analysis_diy import FaceAnalysisDIY
  File "I:\zzzz_stablediffusion-other\zz_LP\LivePortrait\src\utils\face_analysis_diy.py", line 9, in <module>
    from .dependencies.insightface.app import FaceAnalysis
  File "I:\zzzz_stablediffusion-other\zz_LP\LivePortrait\src\utils\dependencies\insightface\__init__.py", line 18, in <module>
    from . import app
  File "I:\zzzz_stablediffusion-other\zz_LP\LivePortrait\src\utils\dependencies\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "I:\zzzz_stablediffusion-other\zz_LP\LivePortrait\src\utils\dependencies\insightface\app\mask_renderer.py", line 8, in <module>
    from ..thirdparty import face3d
  File "I:\zzzz_stablediffusion-other\zz_LP\LivePortrait\src\utils\dependencies\insightface\thirdparty\face3d\__init__.py", line 3, in <module>
    from . import mesh
  File "I:\zzzz_stablediffusion-other\zz_LP\LivePortrait\src\utils\dependencies\insightface\thirdparty\face3d\mesh\__init__.py", line 9, in <module>
    from .cython import mesh_core_cython
ImportError: cannot import name 'mesh_core_cython' from 'src.utils.dependencies.insightface.thirdparty.face3d.mesh.cython' (unknown location)
```

**Comment by oisilener1982** [comment]
Follow the tutorial here. Its so easy
https://www.youtube.com/watch?v=7fTPQJxwJ9k

**Comment by cleardusk** [comment]
We have removed the mesh_core_python module dependency, just pull it to update! @jonk999

**Comment by nitinmukesh** [comment]
Please note the earlier video is removed and new one posted for Windows installation to align with the new updates
https://www.youtube.com/watch?v=bRHf2oQwgG4
