### ISSUE TITLE
ModuleNotFoundError: No module named 'MultiScaleDeformableAttention'

### ISSUE THREAD

**Issue by nitinmukesh** [KwaiVGI/LivePortrait#266]
```
(venv) C:\usable\LivePortrait>python app_animals.py
[23:39:04] Load appearance_feature_extractor from                                           live_portrait_wrapper.py:355
           C:\usable\LivePortrait\pretrained_weights\liveportrait_animals\base_models\appea
           rance_feature_extractor.pth done.
           Load motion_extractor from                                                       live_portrait_wrapper.py:358
           C:\usable\LivePortrait\pretrained_weights\liveportrait_animals\base_models\motio
           n_extractor.pth done.
           Load warping_module from                                                         live_portrait_wrapper.py:361
           C:\usable\LivePortrait\pretrained_weights\liveportrait_animals\base_models\warpi
           ng_module.pth done.
           Load spade_generator from                                                        live_portrait_wrapper.py:364
           C:\usable\LivePortrait\pretrained_weights\liveportrait_animals\base_models\spade
           _generator.pth done.
           Load stitching_retargeting_module from                                           live_portrait_wrapper.py:368
           C:\usable\LivePortrait\pretrained_weights\liveportrait\retargeting_models\stitch
           ing_retargeting_module.pth done.
[23:39:07] FaceAnalysisDIY warmup time: 2.051s                                                   face_analysis_diy.py:79
[23:39:08] LandmarkRunner warmup time: 1.554s                                                human_landmark_runner.py:95
Traceback (most recent call last):
  File "C:\usable\LivePortrait\app_animals.py", line 47, in <module>
    gradio_pipeline_animal: GradioPipelineAnimal = GradioPipelineAnimal(
  File "C:\usable\LivePortrait\src\gradio_pipeline.py", line 341, in __init__
    super().__init__(inference_cfg, crop_cfg)
  File "C:\usable\LivePortrait\src\live_portrait_pipeline_animal.py", line 42, in __init__
    self.cropper: Cropper = Cropper(crop_cfg=crop_cfg, image_type='animal_face', flag_use_half_precision=inference_cfg.flag_use_half_precision)
  File "C:\usable\LivePortrait\src\utils\cropper.py", line 76, in __init__
    from .animal_landmark_runner import XPoseRunner as AnimalLandmarkRunner
  File "C:\usable\LivePortrait\src\utils\animal_landmark_runner.py", line 19, in <module>
    from .dependencies.XPose.models import build_model
  File "C:\usable\LivePortrait\src\utils\dependencies\XPose\models\__init__.py", line 7, in <module>
    from .UniPose.unipose import build_unipose
  File "C:\usable\LivePortrait\src\utils\dependencies\XPose\models\UniPose\__init__.py", line 10, in <module>
    from .unipose import build_unipose
  File "C:\usable\LivePortrait\src\utils\dependencies\XPose\models\UniPose\unipose.py", line 23, in <module>
    from .deformable_transformer import build_deformable_transformer
  File "C:\usable\LivePortrait\src\utils\dependencies\XPose\models\UniPose\deformable_transformer.py", line 30, in <module>
    from .ops.modules import MSDeformAttn
  File "C:\usable\LivePortrait\src\utils\dependencies\XPose\models\UniPose\ops\modules\__init__.py", line 9, in <module>
    from .ms_deform_attn import MSDeformAttn
  File "C:\usable\LivePortrait\src\utils\dependencies\XPose\models\UniPose\ops\modules\ms_deform_attn.py", line 23, in <module>
    from src.utils.dependencies.XPose.models.UniPose.ops.functions.ms_deform_attn_func import MSDeformAttnFunction
  File "C:\usable\LivePortrait\src\utils\dependencies\XPose\models\UniPose\ops\functions\__init__.py", line 9, in <module>
    from .ms_deform_attn_func import MSDeformAttnFunction
  File "C:\usable\LivePortrait\src\utils\dependencies\XPose\models\UniPose\ops\functions\ms_deform_attn_func.py", line 18, in <module>
    import MultiScaleDeformableAttention as MSDA
ModuleNotFoundError: No module named 'MultiScaleDeformableAttention'
```

**Comment by nitinmukesh** [comment]
Completely new installation comes up with another error

```
(venv) C:\tut\LivePortrait>python app_animals.py
[00:02:41] Load appearance_feature_extractor from                                           live_portrait_wrapper.py:355
           C:\tut\LivePortrait\pretrained_weights\liveportrait_animals\base_models\appearan
           ce_feature_extractor.pth done.
[00:02:42] Load motion_extractor from                                                       live_portrait_wrapper.py:358
           C:\tut\LivePortrait\pretrained_weights\liveportrait_animals\base_models\motion_e
           xtractor.pth done.
           Load warping_module from                                                         live_portrait_wrapper.py:361
           C:\tut\LivePortrait\pretrained_weights\liveportrait_animals\base_models\warping_
           module.pth done.
           Load spade_generator from                                                        live_portrait_wrapper.py:364
           C:\tut\LivePortrait\pretrained_weights\liveportrait_animals\base_models\spade_ge
           nerator.pth done.
           Load stitching_retargeting_module from                                           live_portrait_wrapper.py:368
           C:\tut\LivePortrait\pretrained_weights\liveportrait\retargeting_models\stitching
           _retargeting_module.pth done.
2024-08-03 00:02:42.7159042 [E:onnxruntime:Default, provider_bridge_ort.cc:1744 onnxruntime::TryGetProviderInfo_CUDA] C:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1426 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\tut\LivePortrait\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

*************** EP Error ***************
EP Error C:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:866 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-08-03 00:02:42.7462143 [E:onnxruntime:Default, provider_bridge_ort.cc:1744 onnxruntime::TryGetProviderInfo_CUDA] C:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1426 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\tut\LivePortrait\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Traceback (most recent call last):
  File "C:\tut\LivePortrait\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\tut\LivePortrait\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: C:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:866 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\tut\LivePortrait\app_animals.py", line 47, in <module>
    gradio_pipeline_animal: GradioPipelineAnimal = GradioPipelineAnimal(
  File "C:\tut\LivePortrait\src\gradio_pipeline.py", line 341, in __init__
    super().__init__(inference_cfg, crop_cfg)
  File "C:\tut\LivePortrait\src\live_portrait_pipeline_animal.py", line 42, in __init__
    self.cropper: Cropper = Cropper(crop_cfg=crop_cfg, image_type='animal_face', flag_use_half_precision=inference_cfg.flag_use_half_precision)
  File "C:\tut\LivePortrait\src\utils\cropper.py", line 60, in __init__
    self.face_analysis_wrapper = FaceAnalysisDIY(
  File "C:\tut\LivePortrait\src\utils\face_analysis_diy.py", line 37, in __init__
    super().__init__(name=name, root=root, allowed_modules=allowed_modules, **kwargs)
  File "C:\tut\LivePortrait\src\utils\dependencies\insightface\app\face_analysis.py", line 33, in __init__
    model = model_zoo.get_model(onnx_file, **kwargs)
  File "C:\tut\LivePortrait\src\utils\dependencies\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "C:\tut\LivePortrait\src\utils\dependencies\insightface\model_zoo\model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "C:\tut\LivePortrait\src\utils\dependencies\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "C:\tut\LivePortrait\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 432, in __init__
    raise fallback_error from e
  File "C:\tut\LivePortrait\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 427, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "C:\tut\LivePortrait\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: C:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:866 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.
```
