### ISSUE TITLE
Successfully installed all dependencies for app_animal.py on Windows, what is this error

### ISSUE THREAD

**Issue by nitinmukesh** [KwaiVGI/LivePortrait#268]
```
(liveportrait) C:\tut\LivePortrait>python app_animals.py
[01:06:30] Load appearance_feature_extractor from                                           live_portrait_wrapper.py:355
           C:\tut\LivePortrait\pretrained_weights\liveportrait_animals\base_models\appearan
           ce_feature_extractor.pth done.
           Load motion_extractor from                                                       live_portrait_wrapper.py:358
           C:\tut\LivePortrait\pretrained_weights\liveportrait_animals\base_models\motion_e
           xtractor.pth done.
           Load warping_module from                                                         live_portrait_wrapper.py:361
           C:\tut\LivePortrait\pretrained_weights\liveportrait_animals\base_models\warping_
           module.pth done.
[01:06:31] Load spade_generator from                                                        live_portrait_wrapper.py:364
           C:\tut\LivePortrait\pretrained_weights\liveportrait_animals\base_models\spade_ge
           nerator.pth done.
           Load stitching_retargeting_module from                                           live_portrait_wrapper.py:368
           C:\tut\LivePortrait\pretrained_weights\liveportrait\retargeting_models\stitching
           _retargeting_module.pth done.
[01:06:33] FaceAnalysisDIY warmup time: 2.068s                                                   face_analysis_diy.py:79
[01:06:35] LandmarkRunner warmup time: 1.787s                                                human_landmark_runner.py:95
Traceback (most recent call last):
  File "C:\tut\LivePortrait\app_animals.py", line 47, in <module>
    gradio_pipeline_animal: GradioPipelineAnimal = GradioPipelineAnimal(
  File "C:\tut\LivePortrait\src\gradio_pipeline.py", line 341, in __init__
    super().__init__(inference_cfg, crop_cfg)
  File "C:\tut\LivePortrait\src\live_portrait_pipeline_animal.py", line 42, in __init__
    self.cropper: Cropper = Cropper(crop_cfg=crop_cfg, image_type='animal_face', flag_use_half_precision=inference_cfg.flag_use_half_precision)
  File "C:\tut\LivePortrait\src\utils\cropper.py", line 77, in __init__
    self.animal_landmark_runner = AnimalLandmarkRunner(
  File "C:\tut\LivePortrait\src\utils\animal_landmark_runner.py", line 30, in __init__
    self.model = self.load_animal_model(model_config_path, model_checkpoint_path, self.device)
  File "C:\tut\LivePortrait\src\utils\animal_landmark_runner.py", line 43, in load_animal_model
    args = Config.fromfile(model_config_path)
  File "C:\tut\LivePortrait\src\utils\dependencies\XPose\util\config.py", line 186, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename)
  File "C:\tut\LivePortrait\src\utils\dependencies\XPose\util\config.py", line 84, in _file2dict
    shutil.copyfile(filename,
  File "C:\Users\nitin\miniconda3\envs\liveportrait\lib\shutil.py", line 266, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\nitin\\AppData\\Local\\Temp\\tmptu1uoqh9\\tmpcivnuso3.py'
```

MultiScaleDeformableAttention shows installed
```
(liveportrait) C:\tut\LivePortrait>pip list

Package                       Version
----------------------------- ------------

MultiScaleDeformableAttention 1.0
```

There is not such folder/file
'C:\\Users\\nitin\\AppData\\Local\\Temp\\tmptu1uoqh9\\tmpcivnuso3.py'

Which code/file is trying to load this?

**Comment by nitinmukesh** [comment]
Just noticed, with each launch this path keep changing
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\nitin\\AppData\\Local\\Temp\\tmp1u7_ukgl\\tmp1gh_cepk.py'

**Comment by westNeighbor** [comment]
same here:
Traceback (most recent call last):
  File "D:\LivePortrait\inference_animals.py", line 65, in <module>
    main()
  File "D:\LivePortrait\inference_animals.py", line 55, in main
    live_portrait_pipeline_animal = LivePortraitPipelineAnimal(
  File "D:\LivePortrait\src\live_portrait_pipeline_animal.py", line 42, in __init__
    self.cropper: Cropper = Cropper(crop_cfg=crop_cfg, image_type='animal_face', flag_use_half_precision=inference_cfg.flag_use_half_precision)
  File "D:\LivePortrait\src\utils\cropper.py", line 77, in __init__
    self.animal_landmark_runner = AnimalLandmarkRunner(
  File "D:\LivePortrait\src\utils\animal_landmark_runner.py", line 30, in __init__
    self.model = self.load_animal_model(model_config_path, model_checkpoint_path, self.device)
  File "D:\LivePortrait\src\utils\animal_landmark_runner.py", line 43, in load_animal_model
    args = Config.fromfile(model_config_path)
  File "D:\LivePortrait\src\utils\dependencies\XPose\util\config.py", line 186, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename)
  File "D:\LivePortrait\src\utils\dependencies\XPose\util\config.py", line 84, in _file2dict
    shutil.copyfile(filename,
  File "C:\Users\mhzhao\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\mhzhao\\AppData\\Local\\Temp\\tmpmax9zmdz\\tmpowsz7auo.py'

**Comment by nitinmukesh** [comment]
This  error has nothing to do with LivePortrait.
It is an issue with X-Pose

**Comment by zzzweakman** [comment]
Hi @westNeighbor , you can check the issue #270.
