### ISSUE TITLE
ModuleNotFoundError: No module named 'MultiScaleDeformableAttention'

### ISSUE THREAD

**Issue by RichardXU2025** [KwaiVGI/LivePortrait#271]
E:\LivePortrait>conda activate LivePortrait

(LivePortrait) E:\LivePortrait>python app_animals.py
[13:35:01] Load appearance_feature_extractor from                                           live_portrait_wrapper.py:355           E:\LivePortrait\pretrained_weights\liveportrait_animals\base_models\appearance_f
           eature_extractor.pth done.
           Load motion_extractor from                                                       live_portrait_wrapper.py:358           E:\LivePortrait\pretrained_weights\liveportrait_animals\base_models\motion_extra
           ctor.pth done.
[13:35:02] Load warping_module from                                                         live_portrait_wrapper.py:361           E:\LivePortrait\pretrained_weights\liveportrait_animals\base_models\warping_modu
           le.pth done.
           Load spade_generator from                                                        live_portrait_wrapper.py:364           E:\LivePortrait\pretrained_weights\liveportrait_animals\base_models\spade_genera
           tor.pth done.
           Load stitching_retargeting_module from                                           live_portrait_wrapper.py:368           E:\LivePortrait\pretrained_weights\liveportrait\retargeting_models\stitching_ret
           argeting_module.pth done.
[13:35:03] FaceAnalysisDIY warmup time: 1.044s                                                   face_analysis_diy.py:79
[13:35:04] LandmarkRunner warmup time: 0.753s                                                                                                                                                                                     human_landmark_runner.py:95
Traceback (most recent call last):
  File "E:\LivePortrait\app_animals.py", line 47, in <module>
    gradio_pipeline_animal: GradioPipelineAnimal = GradioPipelineAnimal(
  File "E:\LivePortrait\src\gradio_pipeline.py", line 341, in __init__
    super().__init__(inference_cfg, crop_cfg)
  File "E:\LivePortrait\src\live_portrait_pipeline_animal.py", line 42, in __init__
    self.cropper: Cropper = Cropper(crop_cfg=crop_cfg, image_type='animal_face', flag_use_half_precision=inference_cfg.flag_use_half_precision)
  File "E:\LivePortrait\src\utils\cropper.py", line 76, in __init__
    from .animal_landmark_runner import XPoseRunner as AnimalLandmarkRunner
  File "E:\LivePortrait\src\utils\animal_landmark_runner.py", line 19, in <module>
    from .dependencies.XPose.models import build_model
  File "E:\LivePortrait\src\utils\dependencies\XPose\models\__init__.py", line 7, in <module>
    from .UniPose.unipose import build_unipose
  File "E:\LivePortrait\src\utils\dependencies\XPose\models\UniPose\__init__.py", line 10, in <module>
    from .unipose import build_unipose
  File "E:\LivePortrait\src\utils\dependencies\XPose\models\UniPose\unipose.py", line 23, in <module>
    from .deformable_transformer import build_deformable_transformer
  File "E:\LivePortrait\src\utils\dependencies\XPose\models\UniPose\deformable_transformer.py", line 30, in <module>
    from .ops.modules import MSDeformAttn
  File "E:\LivePortrait\src\utils\dependencies\XPose\models\UniPose\ops\modules\__init__.py", line 9, in <module>
    from .ms_deform_attn import MSDeformAttn
  File "E:\LivePortrait\src\utils\dependencies\XPose\models\UniPose\ops\modules\ms_deform_attn.py", line 23, in <module>
    from src.utils.dependencies.XPose.models.UniPose.ops.functions.ms_deform_attn_func import MSDeformAttnFunction
  File "E:\LivePortrait\src\utils\dependencies\XPose\models\UniPose\ops\functions\__init__.py", line 9, in <module>
    from .ms_deform_attn_func import MSDeformAttnFunction
  File "E:\LivePortrait\src\utils\dependencies\XPose\models\UniPose\ops\functions\ms_deform_attn_func.py", line 18, in <module>
    import MultiScaleDeformableAttention as MSDA
ModuleNotFoundError: No module named 'MultiScaleDeformableAttention'

**Comment by zzzweakman** [comment]
You need to build an OP named MultiScaleDeformableAttention first, which is used by [X-Pose](https://github.com/IDEA-Research/X-Pose), a general keypoint detection framework. @RichardXU2025 
```
cd src/utils/dependencies/XPose/models/UniPose/ops
python setup.py build install
cd - # equal to cd ../../../../../../../
```

**Comment by RichardXU2025** [comment]
E:\LivePortrait\src\utils\dependencies\XPose\models\UniPose\ops>python setup.py build install
running build
running build_py
copying functions\ms_deform_attn_func.py -> build\lib.win-amd64-cpython-39\functions
copying functions\__init__.py -> build\lib.win-amd64-cpython-39\functions
copying modules\ms_deform_attn.py -> build\lib.win-amd64-cpython-39\modules
copying modules\ms_deform_attn_key_aware.py -> build\lib.win-amd64-cpython-39\modules
copying modules\__init__.py -> build\lib.win-amd64-cpython-39\modules
running build_ext
e:\miniconda3\envs\LivePortrait\lib\site-packages\torch\utils\cpp_extension.py:499: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
e:\miniconda3\envs\LivePortrait\lib\site-packages\torch\utils\cpp_extension.py:384: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
building 'MultiScaleDeformableAttention' extension
"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DWITH_CUDA -IE:\LivePortrait\src\utils\dependencies\XPose\models\UniPose\ops\src -Ie:\miniconda3\envs\LivePortrait\lib\site-packages\torch\include -Ie:\miniconda3\envs\LivePortrait\lib\site-packages\torch\include\torch\csrc\api\include -Ie:\miniconda3\envs\LivePortrait\lib\site-packages\torch\include\TH -Ie:\miniconda3\envs\LivePortrait\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -Ie:\miniconda3\envs\LivePortrait\include -Ie:\miniconda3\envs\LivePortrait\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /EHsc /TpE:\LivePortrait\src\utils\dependencies\XPose\models\UniPose\ops\src\cpu\ms_deform_attn_cpu.cpp /Fobuild\temp.win-amd64-cpython-39\Release\LivePortrait\src\utils\dependencies\XPose\models\UniPose\ops\src\cpu\ms_deform_attn_cpu.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=MultiScaleDeformableAttention -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++17
ms_deform_attn_cpu.cpp
e:\miniconda3\envs\LivePortrait\lib\site-packages\torch\utils\cpp_extension.py:1967: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\nvcc" -c E:\LivePortrait\src\utils\dependencies\XPose\models\UniPose\ops\src\cuda\ms_deform_attn_cuda.cu -o build\temp.win-amd64-cpython-39\Release\LivePortrait\src\utils\dependencies\XPose\models\UniPose\ops\src\cuda\ms_deform_attn_cuda.obj -IE:\LivePortrait\src\utils\dependencies\XPose\models\UniPose\ops\src -Ie:\miniconda3\envs\LivePortrait\lib\site-packages\torch\include -Ie:\miniconda3\envs\LivePortrait\lib\site-packages\torch\include\torch\csrc\api\include -Ie:\miniconda3\envs\LivePortrait\lib\site-packages\torch\include\TH -Ie:\miniconda3\envs\LivePortrait\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -Ie:\miniconda3\envs\LivePortrait\include -Ie:\miniconda3\envs\LivePortrait\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=MultiScaleDeformableAttention -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 -std=c++17 --use-local-env
ms_deform_attn_cuda.cu
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include\crt/host_config.h(153): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2022 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1\\bin\\nvcc.exe' failed with exit code 2

**Comment by RichardXU2025** [comment]
I have already renewed the whole conda env： pytorch version“conda install dependencies witconda install pytorch==2.3.0 torchvision==0.18.0 torchaudio==2.3.0 pytorch-cuda=12.1 -c pytorch -c nvidiah ”。

**Comment by RichardXU2025** [comment]
bye the way，I‘m the big fan to LivePortrait.

https://github.com/user-attachments/assets/5fb455a6-f379-4894-9368-c123b88c543c

I'm really looking forward to using the new version.

**Comment by zzzweakman** [comment]
@RichardXU2025  You've successfully addressed the CUDA version issue, but you still need to install the correct version of Visual Studio (2017 to 2022). If you find the installation challenging, you can await the update to our One-Click Installer for Windows. 

We really appreciate your love for LivePortrait : )

**Comment by roumankang** [comment]
> @RichardXU2025 You've successfully addressed the CUDA version issue, but you still need to install the correct version of Visual Studio (2017 to 2022). If you find the installation challenging, you can await the update to our One-Click Installer for Windows.
> 
> We really appreciate your love for LivePortrait : )

Hello! I can't get mine work with the similar problem. Seems like it has something to do with vs version, so I stuck on building MultiScaleDeformableAttention. 

running build
running build_py
running build_ext
D:\Face Animation\LivePortrait-Windows-v20240725\LivePortrait_env\lib\site-packages\torch\utils\cpp_extension.py:384: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
building 'MultiScaleDeformableAttention' extension
D:\Face Animation\LivePortrait-Windows-v20240725\LivePortrait_env\lib\site-packages\torch\utils\cpp_extension.py:1967: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Emitting ninja build file D:\Face Animation\LivePortrait-Windows-v20240725\src\utils\dependencies\XPose\models\UniPose\ops\build\temp.win-amd64-cpython-39\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: error: Stat(D:/Face Animation/LivePortrait-Windows-v20240725/src/utils/dependencies/XPose/models/UniPose/ops/build/temp.win-amd64-cpython-39/Release/Face Animation/LivePortrait-Windows-v20240725/src/utils/dependencies/XPose/models/UniPose/ops/src/cpu/ms_deform_attn_cpu.obj): Filename longer than 260 characters
Traceback (most recent call last):
  File "D:\Face Animation\LivePortrait-Windows-v20240725\LivePortrait_env\lib\site-packages\torch\utils\cpp_extension.py", line 2107, in _run_ninja_build
    subprocess.run(
  File "D:\Face Animation\LivePortrait-Windows-v20240725\LivePortrait_env\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Face Animation\LivePortrait-Windows-v20240725\src\utils\dependencies\XPose\models\UniPose\ops\setup.py", line 64, in <module>
    setup(
  File "D:\Face Animation\LivePortrait-Windows-v20240725\LivePortrait_env\lib\site-packages\setuptools\__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
  File "D:\Face Animation\LivePortrait-Windows-v20240725\LivePortrait_env\lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
    return run_commands(dist)
  File "D:\Face Animation\LivePortrait-Windows-v20240725\LivePortrait_env\lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
    dist.run_commands()
  File "D:\Face Animation\LivePortrait-Windows-v20240725\LivePortrait_env\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "D:\Face Animation\LivePortrait-Windows-v20240725\LivePortrait_env\lib\site-packages\setuptools\dist.py", line 967, in run_command
    super().run_command(command)
  File "D:\Face Animation\LivePortrait-Windows-v20240725\LivePortrait_env\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\Face Animation\LivePortrait-Windows-v20240725\LivePortrait_env\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
    self.run_command(cmd_name)
  File "D:\Face Animation\LivePortrait-Windows-v20240725\LivePortrait_env\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "D:\Face Animation\LivePortrait-Windows-v20240725\LivePortrait_env\lib\site-packages\setuptools\dist.py", line 967, in run_command
    super().run_command(command)
  File "D:\Face Animation\LivePortrait-Windows-v20240725\LivePortrait_env\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\Face Animation\LivePortrait-Windows-v20240725\LivePortrait_env\lib\site-packages\setuptools\command\build_ext.py", line 91, in run
    _build_ext.run(self)
  File "D:\Face Animation\LivePortrait-Windows-v20240725\LivePortrait_env\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 359, in run
    self.build_extensions()
  File "D:\Face Animation\LivePortrait-Windows-v20240725\LivePortrait_env\lib\site-packages\torch\utils\cpp_extension.py", line 870, in build_extensions
    build_ext.build_extensions(self)
  File "D:\Face Animation\LivePortrait-Windows-v20240725\LivePortrait_env\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 479, in build_extensions
    self._build_extensions_serial()
  File "D:\Face Animation\LivePortrait-Windows-v20240725\LivePortrait_env\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 505, in _build_extensions_serial
    self.build_extension(ext)
  File "D:\Face Animation\LivePortrait-Windows-v20240725\LivePortrait_env\lib\site-packages\setuptools\command\build_ext.py", line 252, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\Face Animation\LivePortrait-Windows-v20240725\LivePortrait_env\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 560, in build_extension
    objects = self.compiler.compile(
  File "D:\Face Animation\LivePortrait-Windows-v20240725\LivePortrait_env\lib\site-packages\torch\utils\cpp_extension.py", line 842, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "D:\Face Animation\LivePortrait-Windows-v20240725\LivePortrait_env\lib\site-packages\torch\utils\cpp_extension.py", line 1783, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "D:\Face Animation\LivePortrait-Windows-v20240725\LivePortrait_env\lib\site-packages\torch\utils\cpp_extension.py", line 2123, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension



Will continue to figure out, but my question is: When to expect one-click installer for windows? ^_^

**Comment by zzzweakman** [comment]
> Will continue to figure out, but my question is: When to expect one-click installer for windows? ^_^

The one-click installer for Windows has been successfully built and is currently undergoing internal testing. Stay tuned @roumankang ! 😊

**Comment by zzzweakman** [comment]
Hi @roumankang @RichardXU2025,

The new version of the One-Click Installer for Windows is now available! Check out our latest [update](https://github.com/KwaiVGI/LivePortrait?tab=readme-ov-file#-updates)!

**Comment by qiqi0308** [comment]
我也遇到了一样的问题，你后来找到解决方法了么

**Comment by multilogin7** [comment]
I figured out the problem. 
You must run this command
cd src/utils/dependencies/XPose/models/UniPose/ops
python setup.py build install

If you see an error:

RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
RuntimeError:
The detected CUDA version (11.8) mismatches the version that was used to compile
PyTorch (12.1). Please make sure to use the same CUDA versions.

You will need to install the correct pytorch for your version where. You can find the correct command on this site. https://pytorch.org/get-started/previous-versions/
