### ISSUE TITLE
ONNXRuntimeError: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by medalawi** [KwaiVGI/LivePortrait#294]
How to solve this Error?
 [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Add node. Name:'Add_15' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device

```
[14:07:16] Load appearance_feature_extractor from    live_portrait_wrapper.py:43
           /home/ubuntu/Downloads/LivePortrait-main/                            
           pretrained_weights/liveportrait/base_mode                            
           ls/appearance_feature_extractor.pth done.                            
[14:07:17] Load motion_extractor from                live_portrait_wrapper.py:46
           /home/ubuntu/Downloads/LivePortrait-main/                            
           pretrained_weights/liveportrait/base_mode                            
           ls/motion_extractor.pth done.                                        
           Load warping_module from                  live_portrait_wrapper.py:49
           /home/ubuntu/Downloads/LivePortrait-main/                            
           pretrained_weights/liveportrait/base_mode                            
           ls/warping_module.pth done.                                          
[14:07:18] Load spade_generator from                 live_portrait_wrapper.py:52
           /home/ubuntu/Downloads/LivePortrait-main/                            
           pretrained_weights/liveportrait/base_mode                            
           ls/spade_generator.pth done.                                         
           Load stitching_retargeting_module from    live_portrait_wrapper.py:56
           /home/ubuntu/Downloads/LivePortrait-main/                            
           pretrained_weights/liveportrait/retargeti                            
           ng_models/stitching_retargeting_module.pt                            
           h done.                                                              
2024-08-05 14:07:20.980469616 [E:onnxruntime:, sequential_executor.cc:516 ExecuteKernel] Non-zero status code returned while running Add node. Name:'Add_15' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device
Traceback (most recent call last):
  File "/home/ubuntu/Downloads/LivePortrait-main/app.py", line 48, in <module>
    gradio_pipeline = GradioPipeline(
  File "/home/ubuntu/Downloads/LivePortrait-main/src/gradio_pipeline.py", line 42, in __init__
    super().__init__(inference_cfg, crop_cfg)
  File "/home/ubuntu/Downloads/LivePortrait-main/src/live_portrait_pipeline.py", line 39, in __init__
    self.cropper: Cropper = Cropper(crop_cfg=crop_cfg)
  File "/home/ubuntu/Downloads/LivePortrait-main/src/utils/cropper.py", line 66, in __init__
    self.face_analysis_wrapper.warmup()
  File "/home/ubuntu/Downloads/LivePortrait-main/src/utils/face_analysis_diy.py", line 76, in warmup
    self.get(img_bgr)
  File "/home/ubuntu/Downloads/LivePortrait-main/src/utils/face_analysis_diy.py", line 47, in get
    bboxes, kpss = self.det_model.detect(img_bgr, max_num=max_num, metric='default')
  File "/home/ubuntu/Downloads/LivePortrait-main/src/utils/dependencies/insightface/model_zoo/retinaface.py", line 224, in detect
    scores_list, bboxes_list, kpss_list = self.forward(det_img, self.det_thresh)
  File "/home/ubuntu/Downloads/LivePortrait-main/src/utils/dependencies/insightface/model_zoo/retinaface.py", line 152, in forward
    net_outs = self.session.run(self.output_names, {self.input_name : blob})
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Add node. Name:'Add_15' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device

```

**Comment by medalawi** [comment]
I found that my graphic card driver not compatible with the version of installed Cuda 
just uninstall Nvidia driver and Cuda then install driver that support Cuda 12 if it compatible with your graphic card

**Comment by zzzweakman** [comment]
> I found that my graphic card driver not compatible with the version of installed Cuda just uninstall Nvidia driver and Cuda then install driver that support Cuda 12 if it compatible with your graphic card

Thanks for your efforts in finding a solution to this error. I've added a tag for others to reference. 😊

**Comment by BeimingCharles** [comment]
我也有这个问题，但是我怕都是按照版本下载的呀
