### ISSUE TITLE
这个要怎么修改？

### ISSUE THREAD

**Issue by jerrywong1314** [KwaiVGI/LivePortrait#309]
[11:21:01] XPoseRunner warmup time: 1.623s                                                 animal_landmark_runner.py:138
ERROR:    [Errno 10048] error while attempting to bind on address ('127.0.0.1', 8890): 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。
Checking if the server is listening on port 8890...
Server is up and running on http://127.0.0.1:8890
Server is running. Press Ctrl+C to stop.
Traceback (most recent call last):
  File "H:\LivePortrait-Windows-v20240806\LivePortrait-Windows-v20240806\app_animals.py", line 244, in <module>
    demo.launch(
  File "H:\LivePortrait-Windows-v20240806\LivePortrait-Windows-v20240806\LivePortrait_env\lib\site-packages\gradio\blocks.py", line 2327, in launch
    ) = http_server.start_server(
  File "H:\LivePortrait-Windows-v20240806\LivePortrait-Windows-v20240806\LivePortrait_env\lib\site-packages\gradio\http_server.py", line 154, in start_server
    raise OSError(
OSError: Cannot find empty port in range: 8890-8890. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the `server_port` parameter to `launch()`.

**Comment by cleardusk** [comment]
尝试换一个端口？比如 6666 或者其他可访问的；或者尝试加一个option：`--server_name 0.0.0.0`
