### ISSUE TITLE
 无法加载动态链接库(DLL)onnxruntime\capi\onnxruntime_providers_cuda.dll

### ISSUE THREAD

**Issue by Tinaisok** [KwaiVGI/LivePortrait#321]
安装readme文档执行部署，执行第三部 python inference.py 时最开始几秒还能load，然后就出现以下问题，下载了 Dependency Walke软件对dll文件C:\Users\19535\anaconda3\envs\LivePortrait\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll进行了分析，结果是
![屏幕截图 2024-08-14 135554](https://github.com/user-attachments/assets/26a1e1fe-70d5-48fc-a6b5-3e042035e752)
Error: At least one required implicit or forwarded dependency was not found.
Error: A circular dependency was detected.
Warning: At least one delay-load dependency module was not found.
Warning: At least one module has an unresolved import due to a missing export function in a delay-load dependent module.
恳请开发人员帮忙提提建议，如何解决这个问题。
第三部分代码执行结果：
(LivePortrait) C:\Users\19535\LivePortrait>python inference.py
[05:13:17] Load appearance_feature_extractor from                                  live_portrait_wrapper.py:46
           C:\Users\19535\LivePortrait\pretrained_weights\liveportrait\base_models
           \appearance_feature_extractor.pth done.
           Load motion_extractor from                                              live_portrait_wrapper.py:49
           C:\Users\19535\LivePortrait\pretrained_weights\liveportrait\base_models
           \motion_extractor.pth done.
           Load warping_module from                                                live_portrait_wrapper.py:52
           C:\Users\19535\LivePortrait\pretrained_weights\liveportrait\base_models
           \warping_module.pth done.
[05:13:18] Load spade_generator from                                               live_portrait_wrapper.py:55
           C:\Users\19535\LivePortrait\pretrained_weights\liveportrait\base_models
           \spade_generator.pth done.
           Load stitching_retargeting_module from                                  live_portrait_wrapper.py:59
           C:\Users\19535\LivePortrait\pretrained_weights\liveportrait\retargeting
           _models\stitching_retargeting_module.pth done.
2024-08-14 05:13:18.8173059 [E:onnxruntime:Default, provider_bridge_ort.cc:1744 onnxruntime::TryGetProviderInfo_CUDA] C:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1426 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\19535\anaconda3\envs\LivePortrait\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

*************** EP Error ***************
EP Error C:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:866 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),    make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-08-14 05:13:18.8551378 [E:onnxruntime:Default, provider_bridge_ort.cc:1744 onnxruntime::TryGetProviderInfo_CUDA] C:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1426 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\19535\anaconda3\envs\LivePortrait\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Traceback (most recent call last):
  File "C:\Users\19535\anaconda3\envs\LivePortrait\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\19535\anaconda3\envs\LivePortrait\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: C:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:866 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),    make sure they're in the PATH, and that your GPU is supported.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\19535\LivePortrait\inference.py", line 65, in <module>
    main()
  File "C:\Users\19535\LivePortrait\inference.py", line 55, in main
    live_portrait_pipeline = LivePortraitPipeline(
  File "C:\Users\19535\LivePortrait\src\live_portrait_pipeline.py", line 39, in __init__
    self.cropper: Cropper = Cropper(crop_cfg=crop_cfg)
  File "C:\Users\19535\LivePortrait\src\utils\cropper.py", line 63, in __init__
    self.face_analysis_wrapper = FaceAnalysisDIY(
  File "C:\Users\19535\LivePortrait\src\utils\face_analysis_diy.py", line 37, in __init__
    super().__init__(name=name, root=root, allowed_modules=allowed_modules, **kwargs)
  File "C:\Users\19535\LivePortrait\src\utils\dependencies\insightface\app\face_analysis.py", line 33, in __init__
    model = model_zoo.get_model(onnx_file, **kwargs)
  File "C:\Users\19535\LivePortrait\src\utils\dependencies\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "C:\Users\19535\LivePortrait\src\utils\dependencies\insightface\model_zoo\model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "C:\Users\19535\LivePortrait\src\utils\dependencies\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "C:\Users\19535\anaconda3\envs\LivePortrait\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 432, in __init__
    raise fallback_error from e
  File "C:\Users\19535\anaconda3\envs\LivePortrait\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 427, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "C:\Users\19535\anaconda3\envs\LivePortrait\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: C:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:866 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),    make sure they're in the PATH, and that your GPU is supported.

**Comment by zzzweakman** [comment]
@Tinaisok 感谢你提供解决方案，我们为此类问题加上一个标签供其他用户查阅。

Thank you for providing a solution. We have added a tag to this type of issue for reference by other users.

**Comment by BeimingCharles** [comment]
可是onnx我在requirements.txt上就已经下载了呀

**Comment by qhanson** [comment]
``` bash
conda install conda-forge::vs2015_runtime
```
Try to add this runtime, it worked for me
