### ISSUE TITLE
CUDA内存不足

### ISSUE THREAD

**Issue by gaizi123** [KwaiVGI/LivePortrait#326]
Loaded cached embeddings from file.
Checking if the server is listening on port 8890...
Server not ready, waiting 4 seconds...
Traceback (most recent call last):
  File "D:\LivePortrait-Windows-v20240806\app_animals.py", line 47, in <module>
    gradio_pipeline_animal: GradioPipelineAnimal = GradioPipelineAnimal(
  File "D:\LivePortrait-Windows-v20240806\src\gradio_pipeline.py", line 508, in __init__
    super().__init__(inference_cfg, crop_cfg)
  File "D:\LivePortrait-Windows-v20240806\src\live_portrait_pipeline_animal.py", line 42, in __init__
    self.cropper: Cropper = Cropper(crop_cfg=crop_cfg, image_type='animal_face', flag_use_half_precision=inference_cfg.flag_use_half_precision)
  File "D:\LivePortrait-Windows-v20240806\src\utils\cropper.py", line 86, in __init__
    self.animal_landmark_runner.warmup()
  File "D:\LivePortrait-Windows-v20240806\src\utils\animal_landmark_runner.py", line 135, in warmup
    self.run(img_rgb, 'face', 'face', box_threshold=0.0, IoU_threshold=0.0)
  File "D:\LivePortrait-Windows-v20240806\src\utils\animal_landmark_runner.py", line 118, in run
    boxes_filt, keypoints_filt = self.get_unipose_output(image, instance_text_prompt, keypoint_text_prompt, box_threshold, IoU_threshold)
  File "D:\LivePortrait-Windows-v20240806\src\utils\animal_landmark_runner.py", line 75, in get_unipose_output
    "object_embeddings_text": ins_text_embeddings.float(),
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.

**Comment by medalawi** [comment]
what is your GPU VRAM?
what command are you use to run animal mode ?

**Comment by zzzweakman** [comment]
@gaizi123 Thanks for your attention. You'd better make sure your GPU has at least 8GB of VRAM.
