### ISSUE TITLE
 [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from....

### ISSUE THREAD

**Issue by zhangdduo** [KwaiVGI/LivePortrait#39]
hi,gays,
(D:\work\Git\LivePortrait\LivePortrait) D:\work\Git\LivePortrait>python app.py
[09:06:26] Load appearance_feature_extractor done.                                           live_portrait_wrapper.py:29
           Load motion_extractor done.                                                       live_portrait_wrapper.py:32
           Load warping_module done.                                                         live_portrait_wrapper.py:35
[09:06:27] Load spade_generator done.                                                        live_portrait_wrapper.py:38
           Load stitching_retargeting_module done.                                           live_portrait_wrapper.py:42
[09:06:31] LandmarkRunner warmup time: 1.211s                                                      landmark_runner.py:89
Traceback (most recent call last):
  File "D:\work\Git\LivePortrait\app.py", line 28, in <module>
    gradio_pipeline = GradioPipeline(
  File "D:\work\Git\LivePortrait\src\gradio_pipeline.py", line 26, in __init__
    super().__init__(inference_cfg, crop_cfg)
  File "D:\work\Git\LivePortrait\src\live_portrait_pipeline.py", line 39, in __init__
    self.cropper = Cropper(crop_cfg=crop_cfg)
  File "D:\work\Git\LivePortrait\src\utils\cropper.py", line 44, in __init__
    self.face_analysis_wrapper = FaceAnalysisDIY(
  File "D:\work\Git\LivePortrait\src\utils\face_analysis_diy.py", line 37, in __init__
    super().__init__(name=name, root=root, allowed_modules=allowed_modules, **kwargs)
  File "D:\work\Git\LivePortrait\src\utils\dependencies\insightface\app\face_analysis.py", line 33, in __init__
    model = model_zoo.get_model(onnx_file, **kwargs)
  File "D:\work\Git\LivePortrait\src\utils\dependencies\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "D:\work\Git\LivePortrait\src\utils\dependencies\insightface\model_zoo\model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "D:\work\Git\LivePortrait\src\utils\dependencies\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "D:\work\Git\LivePortrait\LivePortrait\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "D:\work\Git\LivePortrait\LivePortrait\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 472, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from D:\work\Git\LivePortrait\src\utils\../../pretrained_weights/insightface\models\buffalo_l\det_10g.onnx failed:Protobuf parsing failed.

**Comment by zzzweakman** [comment]
What version of `onnxruntime-gpu` are you using?

**Comment by zhangdduo** [comment]
> What version of `onnxruntime-gpu` are you using?

Thank you for your reply. I have found the cause, which is due to my det-10g.onnx file being damaged。
