### ISSUE TITLE
torch missing from requirements.txt

### ISSUE THREAD

**Issue by snobu** [KwaiVGI/LivePortrait#415]
```bash
(py310) snobu@LowExpectations:~/LivePortrait$ python app.py
Traceback (most recent call last):
  File "/home/snobu/LivePortrait/app.py", line 12, in <module>
    from src.utils.helper import load_description
  File "/home/snobu/LivePortrait/src/utils/helper.py", line 9, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

```

```bash
(py310) snobu@LowExpectations:~/LivePortrait$ grep -i torch requirements*
requirements_macOS.txt:--extra-index-url https://download.pytorch.org/whl/cpu
requirements_macOS.txt:torch==2.3.0
requirements_macOS.txt:torchvision==0.18.0
requirements_macOS.txt:torchaudio==2.3.0
```

torch is present only in the MacOS dependencies, consider adding it to the base requirements.

**Comment by snobu** [comment]
Nevermind, i should read the README first, maybe that's why they used to call it README.1st.
